FROM node:20-alpine AS build

WORKDIR /app

COPY PollBuilder.Client/package*.json ./
RUN npm install

COPY . .

WORKDIR /app/PollBuilder.Client

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/PollBuilder.Client/dist /usr/share/nginx/html
COPY PollBuilder.Client/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]